services:
  n8n:
    build: .
    container_name: n8n
    image: n8nio/n8n:latest
    restart: unless-stopped
    network_mode: "host"
    ports:
      - "${N8N_PORT}:5678"
    environment:
      - N8N_ENV=${N8N_ENV}
      - N8N_HOST=${N8N_DOMAIN}
      - N8N_PORT=5678
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASS}
      - N8N_ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - N8N_RUNNERS_ENABLED=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - N8N_NODES_PYTHON_PACKAGES_PRELOAD=*
      - WEBHOOK_URL=${N8N_DOMAIN}
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${POSTGRES_HOST}
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASS}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=${TZ}
    volumes:
      - ${N8N_DATA_DIR}:/home/node/.n8n
      - ${N8N_DATA_DIR}/files:/home/node/files